server:
  port: 8080


spring:
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000
        max-total: 2000
    timeout: 0
  # RabbitMq
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest



